# Generated by Django 6.0.3 on 2026-07-16 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entityauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entityauditlog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='entityauditlog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='entityauditlog',
            index=models.Index(fields=['content_type', 'object_id', '-created_at'], name='audit_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='entityauditlog',
            index=models.Index(fields=['workspace', '-created_at'], name='audit_workspace_idx'),
        ),
        migrations.AddIndex(
            model_name='entityauditlog',
            index=models.Index(fields=['actor', '-created_at'], name='audit_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='entityauditlog',
            index=models.Index(fields=['content_type', 'object_id', 'field_name', '-created_at'], name='audit_entity_field_idx'),
        ),
    ]
