# Generated by Django 6.0.3 on 2026-07-27 04:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseActionExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_fingerprint', models.CharField(db_index=True, max_length=255)),
                ('kind', models.CharField(max_length=48)),
                ('spec', models.JSONField()),
                ('inverse_spec', models.JSONField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed — awaiting human approval'), ('executed', 'Executed'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('rolled_back', 'Rolled back')], default='proposed', max_length=16)),
                ('dry_run', models.BooleanField(default=True)),
                ('requested_by', models.CharField(blank=True, default='', max_length=64)),
                ('requested_at', models.DateTimeField()),
                ('justification', models.TextField(blank=True, default='')),
                ('decided_by', models.CharField(blank=True, default='', max_length=64)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_detail', models.JSONField(blank=True, default=dict)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('rollback_detail', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_actions', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['workspace', 'status', '-requested_at'], name='response_re_workspa_d06471_idx'), models.Index(fields=['workspace', 'finding_fingerprint'], name='response_re_workspa_ccee29_idx')],
            },
        ),
    ]
