# Generated by Django 6.0.3 on 2026-08-04 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=100)),
                ('namespace', models.CharField(blank=True, default='', max_length=32)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('user', 'User'), ('system', 'System')], default='user', max_length=16)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='tag_vocabulary', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'is_deleted'], name='tag_ws_deleted_idx'), models.Index(fields=['workspace', 'namespace'], name='tag_ws_namespace_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('workspace', 'slug'), name='uniq_tag_ws_slug_live')],
            },
        ),
    ]
