# Generated by Django 6.0.3 on 2026-07-22 19:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_domains'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, default='pentest', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('generated', 'Generated'), ('approved', 'Approved'), ('failed', 'Failed')], db_index=True, default='draft', max_length=16)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('assembled', models.JSONField(blank=True, default=dict)),
                ('finding_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('pdf_key', models.CharField(blank=True, default='', max_length=512)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deliverable_reports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deliverable_reports', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_reports', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', 'kind', 'status'], name='report_ws_kind_status'), models.Index(fields=['workspace', 'created_at'], name='report_ws_created')],
            },
        ),
    ]
