# Generated by Django 6.0.3 on 2026-07-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AINotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('general', 'General AI activity'), ('teammate_status', 'Orchestrator status'), ('action_created', 'AI action created'), ('action_auto_executed', 'AI action auto executed'), ('action_error', 'AI action error'), ('report_generated', 'AI report generated')], default='general', max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('mention', 'Mention'), ('message', 'Message'), ('system', 'System'), ('ai_event', 'AI Event'), ('report', 'Report')], max_length=32)),
                ('verb', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('object_id', models.CharField(blank=True, help_text='Stored as text to support both integer and UUID targets.', max_length=64, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Soft-deleted by the archival task. Hidden from feeds but retained in DB.')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
