# Generated by Django 6.0.3 on 2026-07-16 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_notifications', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ainotificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ainotificationpreference',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_notification_preferences', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='workspacenotificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacenotificationpreference',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='ainotificationpreference',
            index=models.Index(fields=['user', 'workspace', 'channel'], name='core_notifi_user_id_4c07ff_idx'),
        ),
        migrations.AddIndex(
            model_name='ainotificationpreference',
            index=models.Index(fields=['workspace', 'channel'], name='core_notifi_workspa_d940e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ainotificationpreference',
            unique_together={('user', 'workspace', 'channel')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='core_notifi_recipie_d26ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_17c633_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_archived', '-created_at'], name='core_notifi_recipie_bf5084_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='core_notifi_notific_8de63e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['workspace'], name='core_notifi_workspa_e2b1cf_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'workspace'], name='core_notifi_recipie_d6f31a_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacenotificationpreference',
            index=models.Index(fields=['user', 'workspace'], name='core_notifi_user_id_6976d1_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacenotificationpreference',
            index=models.Index(fields=['workspace'], name='core_notifi_workspa_6c6613_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacenotificationpreference',
            unique_together={('user', 'workspace')},
        ),
    ]
