# Generated by Django 6.0.3 on 2026-08-04 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_notifications', '0003_pushsubscription_notificationdelivery_and_more'),
        ('integrations', '0011_deliveryconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedup_key', models.CharField(max_length=255)),
                ('event_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_deliveries', to='integrations.deliveryconnection')),
            ],
            options={
                'indexes': [models.Index(fields=['connection', 'status'], name='core_notifi_connect_5d9b14_idx'), models.Index(fields=['event_key', 'status'], name='core_notifi_event_k_a4a7fc_idx')],
                'constraints': [models.UniqueConstraint(fields=('connection', 'dedup_key'), name='uniq_external_delivery_connection_dedup')],
            },
        ),
    ]
