"""
Storage backends for Django's Static and Media files.

- Local environments (local, dev, test) use FileSystemStorage so
  developer iteration is fast and offline.
- Production uses S3MediaStorage (django-storages S3Boto3Storage)
  scoped to the `media/` prefix of the shared data bucket. The
  EC2 disk has no role in serving user uploads in prod, so the
  instance becomes effectively stateless from a media standpoint.

Static files always stay on disk -- they're regenerated by
`collectstatic` on every deploy and there's nothing to back up.
"""
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from storages.backends.s3boto3 import S3Boto3Storage


class LocalMediaStorage(FileSystemStorage):
    """Local file storage for Django's Media files."""

    def __init__(self, *args, **kwargs):
        kwargs['location'] = settings.MEDIA_ROOT
        kwargs['base_url'] = settings.MEDIA_URL
        super().__init__(*args, **kwargs)


class LocalStaticStorage(FileSystemStorage):
    """Local file storage for Django's Static files."""

    def __init__(self, *args, **kwargs):
        kwargs['location'] = settings.STATIC_ROOT
        kwargs['base_url'] = settings.STATIC_URL
        super().__init__(*args, **kwargs)


class S3MediaStorage(S3Boto3Storage):
    """Production media storage on S3.

    Lives at `s3://<AWS_STORAGE_BUCKET_NAME>/media/` -- the location
    prefix is set via the AWS_LOCATION setting so we share the data
    bucket with backup/ without IAM crossover (the EC2 instance role
    cannot write here; only the data-bucket-app IAM user can).

    Defaults are wired below so a missing AWS_LOCATION never silently
    drops uploads into the bucket root alongside backups. If you see
    `media/` objects appearing in `backup/`, this default has been
    overridden somewhere it shouldn't be.
    """

    location = "media"
    file_overwrite = False  # ← keeps Django's upload_to=... unique
    # suffix behaviour intact instead of overwriting on hash collision.
    default_acl = None  # ← bucket has block-public-access enforced;
    # don't try to set per-object ACLs that would silently fail.
    querystring_auth = True  # ← serve signed URLs by default so the
    # bucket can stay fully private; downstream serializers can opt
    # public objects out per-field if needed.