# Generated by Django 6.0.3 on 2026-07-16 23:52

import infrastructure.persistence.notifications.userpreferences.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darkmode', models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark')], default='Dark', max_length=20)),
                ('language', models.CharField(blank=True, max_length=250)),
                ('email_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=False)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('ui_version', models.CharField(choices=[('v1', 'V1 Classic'), ('v2', 'V2 Command Center')], default='v1', help_text='Which UI variant the user prefers (v1=classic, v2=command center).', max_length=10)),
                ('recommendations_personalized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspacePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(blank=True, default=infrastructure.persistence.notifications.userpreferences.models.default_workspace_notification_settings)),
            ],
        ),
    ]
