# Generated by Django 6.0.3 on 2026-08-03 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpssSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_date', models.DateField(help_text="EPSS feed's own score_date — the dated snapshot key.")),
                ('model_version', models.CharField(blank=True, default='', help_text='EPSS model version, e.g. v2025.03.14.', max_length=32)),
                ('fetched_at', models.DateTimeField(help_text='When this pull was ingested (wall clock).')),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', help_text='Optional content checksum of the pull.', max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['-score_date'], name='epss_snapshot_latest_idx')],
                'constraints': [models.UniqueConstraint(fields=('score_date',), name='uniq_epss_snapshot_date')],
            },
        ),
        migrations.CreateModel(
            name='KevSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('catalog_version', models.CharField(help_text='CISA KEV catalogVersion, e.g. 2026.08.01 — the snapshot key.', max_length=32)),
                ('fetched_at', models.DateTimeField()),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['-fetched_at'], name='kev_snapshot_latest_idx')],
                'constraints': [models.UniqueConstraint(fields=('catalog_version',), name='uniq_kev_snapshot_version')],
            },
        ),
        migrations.CreateModel(
            name='EpssScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cve', models.CharField(help_text='CVE id, e.g. CVE-2024-3094.', max_length=32)),
                ('epss', models.FloatField(help_text='Probability [0-1] of exploitation in the next 30 days.')),
                ('percentile', models.FloatField(help_text='Percentile rank [0-1] among all scored CVEs.')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='vuln_intel.epsssnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'cve'], name='epss_score_snap_cve_idx')],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'cve'), name='uniq_epss_score_identity')],
            },
        ),
        migrations.CreateModel(
            name='KevEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cve', models.CharField(max_length=32)),
                ('date_added', models.DateField(blank=True, help_text='When CISA added the CVE to the catalog.', null=True)),
                ('known_ransomware', models.BooleanField(default=False, help_text="knownRansomwareCampaignUse == 'Known'.")),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vuln_intel.kevsnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'cve'], name='kev_entry_snap_cve_idx')],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'cve'), name='uniq_kev_entry_identity')],
            },
        ),
    ]
