# Generated by Django 6.0.3 on 2026-07-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('price', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('billing_interval', models.CharField(default='month', max_length=10)),
                ('interval_count', models.PositiveIntegerField(default=1)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'team_plan',
            },
        ),
    ]
