"""Workflow error helpers and exception handler mixin.

Infrastructure-layer concern: wraps DRF errors in the workflow error envelope.
"""

from __future__ import annotations

from typing import Any, Dict, Tuple


class WorkflowExceptionHandlerMixin:
    """Wrap DRF errors in the workflow error envelope.

    CONSTRAINTS:
    - Only formats responses generated by DRF's exception handler.
    - Preserves an existing workflow envelope to avoid double-wrapping.
    - Does not alter successful responses.
    """

    def handle_exception(self, exc):
        handler = self.get_exception_handler()
        context = self.get_exception_handler_context()
        response = handler(exc, context)
        if response is None:
            return super().handle_exception(exc)

        if _is_workflow_envelope(response.data):
            return response

        detail, fields = _extract_detail_fields(response.data)
        code = getattr(exc, "default_code", "error") or "error"
        response.data = {"detail": detail, "code": code, "fields": fields}
        return response


def _is_workflow_envelope(data: Any) -> bool:
    if not isinstance(data, dict):
        return False
    return {"detail", "code", "fields"}.issubset(data.keys())


def _extract_detail_fields(data: Any) -> Tuple[str, Dict[str, Any]]:
    if isinstance(data, dict):
        if "detail" in data:
            detail = data.get("detail") or "Request failed."
            fields = {key: value for key, value in data.items() if key != "detail"}
            if isinstance(detail, (list, dict)):
                return "Validation error.", fields or {"non_field_errors": detail}
            return str(detail), fields
        return "Validation error.", data

    if isinstance(data, list):
        return "Validation error.", {"non_field_errors": data}

    if data is None:
        return "Request failed.", {}

    return str(data), {}
