# Generated by Django 6.0.3 on 2026-07-16 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Platform-level toggle. False = provider not available to any workspace.')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Provider-level config (e.g. base_url for Ollama, deployment info for Azure).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_model_providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-friendly display name.', max_length=150)),
                ('model_id', models.CharField(help_text="The exact model ID sent to the provider API (e.g. 'gpt-4o', 'claude-opus-4-20250514').", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tier', models.CharField(choices=[('tier_1', 'Tier 1 — Fast & cheap'), ('tier_2', 'Tier 2 — Balanced'), ('tier_3', 'Tier 3 — Most capable')], default='tier_2', max_length=10)),
                ('supports_streaming', models.BooleanField(default=True)),
                ('supports_tool_use', models.BooleanField(default=True)),
                ('supports_vision', models.BooleanField(default=False)),
                ('context_window', models.PositiveIntegerField(default=128000, help_text='Max context window in tokens.')),
                ('max_output_tokens', models.PositiveIntegerField(default=4096, help_text='Max output tokens per request.')),
                ('input_cost_per_1k', models.DecimalField(decimal_places=6, default=0, help_text='Cost per 1K input tokens in USD.', max_digits=10)),
                ('output_cost_per_1k', models.DecimalField(decimal_places=6, default=0, help_text='Cost per 1K output tokens in USD.', max_digits=10)),
                ('is_available', models.BooleanField(default=False, help_text='True when the platform has API keys configured and the model is ready to use.')),
                ('is_default', models.BooleanField(default=False, help_text="The default model for new workspaces that haven't configured AI yet.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='llms.aimodelprovider')),
            ],
            options={
                'db_table': 'ai_models',
                'ordering': ['provider', 'tier', 'name'],
                'indexes': [models.Index(fields=['is_available', 'provider'], name='ai_model_avail_provider_idx'), models.Index(fields=['is_default'], name='ai_model_default_idx')],
            },
        ),
    ]
