# Generated by Django 6.0.3 on 2026-07-16 23:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('goal', models.CharField(max_length=64)),
                ('is_custom', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('paused', 'paused'), ('archived', 'archived')], default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('graph', models.JSONField(default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('paused', 'paused'), ('completed', 'completed'), ('failed', 'failed'), ('canceled', 'canceled')], default='queued', max_length=16)),
                ('trigger_type', models.CharField(max_length=64)),
                ('trigger_payload', models.JSONField(default=dict)),
                ('target_type', models.CharField(choices=[('contact', 'contact'), ('group', 'group')], max_length=16)),
                ('target_id', models.CharField(max_length=64)),
                ('current_node_id', models.CharField(blank=True, max_length=128)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workflows.workflow')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowRunIdempotency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('contact', 'contact'), ('group', 'group')], max_length=16)),
                ('target_id', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_entries', to='workflows.workflowrun')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_idempotency_keys', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cadence', models.CharField(choices=[('interval', 'Every N hours'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=16)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('run_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('audience', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_schedules', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='workflows.workflow')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_schedules', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(choices=[('entered', 'entered'), ('completed', 'completed'), ('failed', 'failed'), ('branched', 'branched')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workflows.workflowrun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('waiting', 'waiting'), ('waiting_input', 'waiting_input'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('output', models.JSONField(default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_states', to='workflows.workflowrun')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=64)),
                ('version', models.CharField(default='1', max_length=16)),
                ('is_system', models.BooleanField(default=False)),
                ('default_graph', models.JSONField(default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_templates', to=settings.AUTH_USER_MODEL)),
                ('visible_to_groups', models.ManyToManyField(blank=True, help_text='Groups that can see this template. Empty means visible to all.', related_name='visible_workflow_templates', to='workspaces.workspacegroup')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='workflows.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('graph', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_workflow_versions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflows.workflow')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('directory', 'directory'), ('task', 'task'), ('event', 'event'), ('campaign', 'campaign'), ('sponsorship', 'sponsorship'), ('project', 'project'), ('grant', 'grant'), ('document', 'document'), ('form', 'form'), ('communication', 'communication'), ('budget', 'budget'), ('receipt', 'receipt')], max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=64, null=True)),
                ('trigger_type', models.CharField(max_length=64)),
                ('config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='workflows.workflow')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workflow', 'source_type'], name='workflows_w_workflo_6bd4ca_idx'), models.Index(fields=['source_type', 'source_id'], name='workflows_w_source__1d4e0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('contact', 'contact'), ('group', 'group')], max_length=16)),
                ('target_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('exited', 'Exited')], default='active', max_length=16)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='workflows.workflow')),
            ],
            options={
                'ordering': ('-entered_at',),
                'indexes': [models.Index(fields=['workflow', 'status'], name='workflows_w_workflo_64d466_idx'), models.Index(fields=['target_type', 'target_id'], name='workflows_w_target__b4a7ad_idx')],
                'unique_together': {('workflow', 'target_type', 'target_id')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('directory', 'directory'), ('task', 'task'), ('event', 'event'), ('campaign', 'campaign'), ('sponsorship', 'sponsorship'), ('project', 'project'), ('grant', 'grant'), ('document', 'document'), ('form', 'form'), ('communication', 'communication'), ('budget', 'budget'), ('receipt', 'receipt')], max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=64, null=True)),
                ('trigger_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('processed', 'processed'), ('failed', 'failed')], default='pending', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', 'status'], name='workflows_w_workspa_83ddc1_idx'), models.Index(fields=['trigger_type', 'source_type'], name='workflows_w_trigger_a022fe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['workflow', 'status'], name='workflows_w_workflo_92e6ff_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['target_type', 'target_id'], name='workflows_w_target__bde9a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowrunidempotency',
            unique_together={('workflow', 'target_type', 'target_id', 'idempotency_key')},
        ),
        migrations.AddIndex(
            model_name='workflowschedule',
            index=models.Index(fields=['enabled', 'next_run_at'], name='workflows_w_enabled_e90e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowschedule',
            index=models.Index(fields=['workspace'], name='workflows_w_workspa_67576f_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowschedule',
            index=models.Index(fields=['workflow'], name='workflows_w_workflo_dc32f1_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstepevent',
            index=models.Index(fields=['run', 'node_id'], name='workflows_w_run_id_2df825_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstepstate',
            unique_together={('run', 'node_id')},
        ),
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['workspace', 'category'], name='workflows_w_workspa_30483f_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['is_system'], name='workflows_w_is_syst_fb2e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['workspace', 'status'], name='workflows_w_workspa_1e5078_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['template'], name='workflows_w_templat_398f11_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowversion',
            unique_together={('workflow', 'version')},
        ),
    ]
