# Generated by Django 6.0.3 on 2026-07-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowbinding',
            name='source_type',
            field=models.CharField(choices=[('task', 'task'), ('project', 'project'), ('document', 'document'), ('finding', 'finding')], max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='source_type',
            field=models.CharField(choices=[('task', 'task'), ('project', 'project'), ('document', 'document'), ('finding', 'finding')], max_length=32),
        ),
    ]
