# Generated by Django 6.0.3 on 2026-07-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_workflowbinding_source_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowenrollment',
            name='target_type',
            field=models.CharField(choices=[('contact', 'contact'), ('group', 'group'), ('finding', 'finding')], max_length=16),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='target_type',
            field=models.CharField(choices=[('contact', 'contact'), ('group', 'group'), ('finding', 'finding')], max_length=16),
        ),
        migrations.AlterField(
            model_name='workflowrunidempotency',
            name='target_type',
            field=models.CharField(choices=[('contact', 'contact'), ('group', 'group'), ('finding', 'finding')], max_length=16),
        ),
    ]
