# Generated by Django 6.0.3 on 2026-07-26 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=64)),
                ('target_ref', models.CharField(blank=True, default='', max_length=512)),
                ('connection_id', models.UUIDField(blank=True, null=True)),
                ('account_id', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('engine', models.CharField(blank=True, default='', max_length=32)),
                ('engine_version', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('total_checks', models.PositiveIntegerField(default=0)),
                ('passed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_runs', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='scanrun_ws_created_idx'), models.Index(fields=['workspace', 'source', '-created_at'], name='scanrun_ws_source_idx')],
            },
        ),
    ]
