# Generated by Django 6.0.3 on 2026-08-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrun',
            name='trigger',
            field=models.CharField(default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='scanrun',
            name='triggered_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
