# Generated by Django 6.0.3 on 2026-08-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0002_scanrun_trigger_scanrun_triggered_by_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrun',
            name='raw_artifact_ref',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
