# Generated by Django 6.0.3 on 2026-07-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
        ('workspaces', '0003_paymentprovider_donationform_paymentevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='domains',
            field=models.ManyToManyField(blank=True, related_name='workspaces', to='domains.domain'),
        ),
    ]
