# Generated by Django 6.0.3 on 2026-08-14 02:00
#
# Hand-corrected 2026-08-14: the auto-generated version used ``AlterField`` to
# repoint ``Workspace.tags`` / ``WorkspaceMembership.tags`` from the deleted
# ``workspaces.Tag`` (bigint pk) to ``tagging.Tag`` (UUID pk). On PostgreSQL that
# emits
#
#     ALTER TABLE "workspaces_workspace_tags"
#       ALTER COLUMN "tag_id" TYPE uuid USING "tag_id"::uuid
#
# which fails with ``cannot cast type bigint to uuid`` — there is no such cast.
# The through table has to be DROPPED and RECREATED, which is what
# ``RemoveField`` + ``AddField`` produce. Safe and lossless here: both M2Ms were
# verified empty before the change (workspaces.Tag had 0 rows; 0 memberships
# carried a tag).
#
# This was not caught before it hit a real database because the test settings run
# on SQLite, which rebuilds a table wholesale on ALTER and therefore accepts a
# type change PostgreSQL rejects. A migration that only ever ran on SQLite has
# not been tested.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tagging", "0001_initial"),
        ("workspaces", "0004_workspace_domains"),
    ]

    operations = [
        # WorkspaceComment lost tagging entirely (nonprofit-era hashtag scraper).
        migrations.RemoveField(
            model_name="workspacecomment",
            name="tags",
        ),
        # Drop the bigint-keyed through tables …
        migrations.RemoveField(
            model_name="workspace",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="workspacemembership",
            name="tags",
        ),
        # … then recreate them against the UUID-keyed canonical vocabulary.
        migrations.AddField(
            model_name="workspace",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="tagged_workspaces", to="tagging.tag"),
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="workspace_memberships", to="tagging.tag"),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
