# Generated by Django 6.0.3 on 2026-08-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0001_initial'),
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacecomment',
            name='tags',
        ),
        migrations.AlterField(
            model_name='workspace',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_workspaces', to='tagging.tag'),
        ),
        migrations.AlterField(
            model_name='workspacemembership',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='workspace_memberships', to='tagging.tag'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
