# Generated by Django 6.0.3 on 2026-08-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_remove_workspacecomment_tags_alter_workspace_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='autonomy_mode',
            field=models.CharField(choices=[('manual', 'Manual — the agent proposes; nothing is changed for you'), ('assist', 'Assist — the agent makes reversible changes; irreversible needs approval'), ('autonomous', 'Autonomous — unattended runs, same ceiling as Assist')], default='assist', help_text="How much the AI may do in this workspace (ADR 0035). Orthogonal to ai_teammate_enabled, which is the power switch: OFF means nothing runs at all, while this decides what a run that DOES happen may change. Default 'assist' because that is what the product did before this field existed — nobody's behaviour changes on deploy. Note that 'autonomous' does NOT widen the risk ceiling (D3): irreversible actions still require human approval in every mode.", max_length=16),
        ),
    ]
