# Generated by Django 6.0.3 on 2026-07-16 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broadcast', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banner',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['scope', 'is_active'], name='banner_scope_active_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['starts_at', 'ends_at'], name='banner_schedule_idx'),
        ),
    ]
