# Generated by Django 6.0.3 on 2026-07-26 03:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aws_account_link_id', models.UUIDField(blank=True, null=True)),
                ('provider', models.CharField(default='aws', max_length=16)),
                ('arn', models.CharField(help_text='ARN / globally-unique resource id — the dedup key.', max_length=512)),
                ('asset_urn', models.CharField(help_text='AssetUrn.value — cross-pillar correlation key.', max_length=512)),
                ('resource_type', models.CharField(help_text='e.g. aws_ec2_instance, aws_iam_role, aws_s3_bucket.', max_length=64)),
                ('region', models.CharField(blank=True, default='', max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('exposure', models.CharField(default='private', help_text='public | internal | private (derived).', max_length=16)),
                ('attributes', models.JSONField(default=dict, help_text='Normalized resource config (JSON-safe).')),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_assets', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CloudAssetEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation', models.CharField(help_text='Typed relationship, e.g. can_assume, attached_to, allows_ingress_from, has_policy.', max_length=32)),
                ('attributes', models.JSONField(default=dict)),
                ('last_seen_at', models.DateTimeField()),
                ('dst_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='cloud_graph.cloudasset')),
                ('src_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='cloud_graph.cloudasset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_asset_edges', to='workspaces.workspace')),
            ],
        ),
        migrations.AddIndex(
            model_name='cloudasset',
            index=models.Index(fields=['workspace', 'resource_type'], name='casset_ws_type_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudasset',
            index=models.Index(fields=['workspace', 'asset_urn'], name='casset_ws_urn_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudasset',
            index=models.Index(fields=['workspace', 'exposure'], name='casset_ws_exposure_idx'),
        ),
        migrations.AddConstraint(
            model_name='cloudasset',
            constraint=models.UniqueConstraint(fields=('workspace', 'arn'), name='uniq_cloud_asset_identity'),
        ),
        migrations.AddIndex(
            model_name='cloudassetedge',
            index=models.Index(fields=['workspace', 'relation'], name='cedge_ws_relation_idx'),
        ),
        migrations.AddConstraint(
            model_name='cloudassetedge',
            constraint=models.UniqueConstraint(fields=('src_asset', 'dst_asset', 'relation'), name='uniq_cloud_asset_edge'),
        ),
    ]
