# Generated by Django 6.0.3 on 2026-07-26 19:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_graph', '0001_initial'),
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(help_text='AttackPathCategory.value — the toxic-combo kind.', max_length=32)),
                ('severity', models.CharField(help_text='Severity.value', max_length=16)),
                ('risk_band', models.CharField(help_text='RiskBand.value — green | amber | red.', max_length=8)),
                ('risk_score', models.FloatField(help_text='0–100 contextual risk.')),
                ('entry_asset_id', models.UUIDField()),
                ('entry_asset_urn', models.CharField(max_length=512)),
                ('entry_label', models.CharField(max_length=255)),
                ('target_asset_id', models.UUIDField()),
                ('target_asset_urn', models.CharField(max_length=512)),
                ('target_label', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('explanation', models.TextField(blank=True, default='')),
                ('length', models.PositiveIntegerField(default=0, help_text='Hop count (edges) entry → target.')),
                ('legs', models.JSONField(default=list, help_text='Ordered hops: [{src_id, src_label, relation, dst_id, dst_label}].')),
                ('asset_urns', models.JSONField(default=list, help_text='Ordered node chain (entry → … → target).')),
                ('computed_at', models.DateTimeField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_paths', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', '-risk_score'], name='apath_ws_risk_idx'), models.Index(fields=['workspace', 'category'], name='apath_ws_category_idx')],
            },
        ),
    ]
