# Generated by Django 6.0.3 on 2026-08-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_graph', '0002_attackpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackpath',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cloudasset',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cloudassetedge',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
