# Generated by Django 6.0.3 on 2026-07-17 02:40

import django.db.models.deletion
import django.utils.timezone
import infrastructure.persistence.ai.aggregations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_paymentprovider_donationform_paymentevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('preferred_model', 'Preferred model'), ('fallback_model', 'Fallback model')], max_length=32)),
                ('old_value', models.CharField(blank=True, default='', max_length=100)),
                ('new_value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_model_change_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_model_change_events', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='ai_model_change_ws_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIModelDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('model_used', models.CharField(max_length=100)),
                ('llm_calls', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveBigIntegerField(default=0)),
                ('completion_tokens', models.PositiveBigIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('latency_p50_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_p95_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_model_daily_metrics', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-date', 'model_used'],
                'indexes': [models.Index(fields=['workspace', '-date'], name='ai_model_metric_ws_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'date', 'model_used'), name='uniq_ws_date_model_metric')],
            },
        ),
        migrations.CreateModel(
            name='AIWorkspaceDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('runs_total', models.PositiveIntegerField(default=0)),
                ('runs_completed', models.PositiveIntegerField(default=0)),
                ('runs_failed', models.PositiveIntegerField(default=0)),
                ('assistant_messages', models.PositiveIntegerField(default=0)),
                ('feedback_up', models.PositiveIntegerField(default=0)),
                ('feedback_down', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_workspace_daily_metrics', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['workspace', '-date'], name='ai_ws_metric_ws_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'date'), name='uniq_ws_date_workspace_metric')],
            },
        ),
        migrations.CreateModel(
            name='IndexFreshnessSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When this measurement was taken. Always in UTC.')),
                ('latest_event_time', models.DateTimeField(blank=True, help_text='Most recent timestamp across the watched domain models. NULL means the workspace has no events at all — treated as fresh by the SLO (lag = 0).', null=True)),
                ('latest_index_time', models.DateTimeField(blank=True, help_text='Most recent EmbeddingChunk.created_at for this workspace. NULL means the workspace has never been indexed.', null=True)),
                ('lag_seconds', models.PositiveIntegerField(help_text='max(0, latest_event_time - latest_index_time). Clamped to 0 when the index is newer than the event (the workspace is fully fresh).')),
                ('sla_target_seconds', models.PositiveIntegerField(help_text="The SLO target lag at measurement time. Recorded per row so an SLO retune doesn't retroactively re-categorise historical samples.")),
                ('sla_met', models.BooleanField(help_text='True iff lag_seconds <= sla_target_seconds. Computed at write time so the global compliance query is a fast aggregate without recomputing per row.')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_freshness_samples', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-sample_time', 'workspace_id'],
                'indexes': [models.Index(fields=['workspace', '-sample_time'], name='ai_aggregat_workspa_aacc6c_idx'), models.Index(fields=['-sample_time', 'sla_met'], name='ai_aggregat_sample__4eb4d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_messages_sent', models.PositiveIntegerField(default=0)),
                ('daily_window_start', models.DateField(db_index=True, default=infrastructure.persistence.ai.aggregations.models._today_utc, help_text='Date this daily-messages counter belongs to. If older than today, the counter is stale and reads should return 0 until the daily reset task rolls it forward.')),
                ('monthly_tokens_used', models.PositiveBigIntegerField(default=0)),
                ('monthly_window_start', models.DateField(db_index=True, default=infrastructure.persistence.ai.aggregations.models._first_of_month_utc, help_text='First day of the calendar month this monthly-tokens counter belongs to. If from a prior month, the counter is stale and reads should return 0 until the monthly reset task rolls it forward.')),
                ('monthly_runs_used', models.PositiveIntegerField(default=0)),
                ('monthly_runs_window_start', models.DateField(db_index=True, default=infrastructure.persistence.ai.aggregations.models._first_of_month_utc, help_text='First day of the calendar month this monthly-runs counter belongs to. If from a prior month, the counter is stale and reads return 0 until the monthly reset task rolls it forward.')),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['daily_window_start'], name='ai_aggregat_daily_w_999229_idx'), models.Index(fields=['monthly_window_start'], name='ai_aggregat_monthly_67e832_idx')],
            },
        ),
    ]
