# Generated by Django 6.0.3 on 2026-07-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('token', models.CharField(blank=True, db_index=True, help_text='Single-use magic-link token. Hex-encoded 32-byte secret.', max_length=64)),
                ('persona', models.CharField(choices=[('admin', 'Admin'), ('contributor', 'Contributor'), ('sponsor', 'Sponsor'), ('volunteer', 'Volunteer'), ('auditor', 'Auditor'), ('board_member', 'Board Member')], default='contributor', help_text='Persona the invitee will receive on accept. See ADR 0002.', max_length=20)),
                ('role', models.CharField(default='member', help_text='WorkspaceMembership.role to grant on accept (RBAC tier).', max_length=20)),
                ('permission_group_ids', models.JSONField(blank=True, default=list, help_text='UUIDs of WorkspaceGroups to enroll the invitee into when the invitation is accepted.')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='invited', max_length=20)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('department', 'Department'), ('project_team', 'Project Team'), ('ai_agents', 'AI Agents')], db_index=True, default='department', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('privacy', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='private', max_length=8)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('plan_end_date', models.DateTimeField(blank=True, null=True)),
                ('plan_status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
