# Generated by Django 6.0.3 on 2026-07-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='kind',
            field=models.CharField(choices=[('department', 'Department'), ('project_team', 'Project Team'), ('ai_agents', 'AI Agents'), ('blue_team', 'Blue Team'), ('red_team', 'Red Team')], db_index=True, default='department', max_length=20),
        ),
    ]
