# Generated by Django 6.0.3 on 2026-07-16 23:52

import infrastructure.persistence.uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=infrastructure.persistence.uploads.models._upload_to)),
                ('workspace_id', models.CharField(blank=True, help_text='ID of the workspace/organization this file belongs to', max_length=36, null=True)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=20)),
                ('processing_status', models.CharField(choices=[('not_indexed', 'Not indexed'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_indexed', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('index_requested_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_text', models.TextField(blank=True, null=True)),
                ('pdf_page_count', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('ai_chat', 'AI Chat'), ('expense_import', 'Expense Import'), ('income_import', 'Income Import'), ('budget_import', 'Budget Import'), ('knowledge_base', 'Knowledge Base'), ('manual_upload', 'Manual Upload'), ('other', 'Other')], default='manual_upload', max_length=32)),
                ('ai_insights', models.JSONField(blank=True, default=dict, help_text='AI-extracted insights about this document.')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
