# Generated by Django 6.0.3 on 2026-08-10 03:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provenance", "0002_provenanceresource_asset_urn"),
        ("workspaces", "0004_workspace_domains"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="provenanceactor",
            name="source_system",
            field=models.CharField(
                choices=[
                    ("internal", "autosec internal (audit trail)"),
                    ("ai", "autosec AI agents"),
                    ("identity", "autosec identity (sessions / roles)"),
                    ("aws", "AWS (IAM / CloudTrail)"),
                    ("okta", "Okta"),
                    ("google_workspace", "Google Workspace"),
                    ("slack", "Slack"),
                    ("github", "GitHub"),
                    ("agent_runtime", "Customer AI agent runtime (reported telemetry)"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="provenanceevent",
            name="origin",
            field=models.CharField(
                choices=[
                    ("audit_log", "EntityAuditLog"),
                    ("ai_action", "AI action"),
                    ("identity_session", "Identity session"),
                    ("vendor_log", "Vendor audit log"),
                    ("agent_runtime", "Customer agent runtime telemetry"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="provenanceevent",
            name="source_system",
            field=models.CharField(
                choices=[
                    ("internal", "autosec internal (audit trail)"),
                    ("ai", "autosec AI agents"),
                    ("identity", "autosec identity (sessions / roles)"),
                    ("aws", "AWS (IAM / CloudTrail)"),
                    ("okta", "Okta"),
                    ("google_workspace", "Google Workspace"),
                    ("slack", "Slack"),
                    ("github", "GitHub"),
                    ("agent_runtime", "Customer AI agent runtime (reported telemetry)"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="provenanceresource",
            name="source_system",
            field=models.CharField(
                choices=[
                    ("internal", "autosec internal (audit trail)"),
                    ("ai", "autosec AI agents"),
                    ("identity", "autosec identity (sessions / roles)"),
                    ("aws", "AWS (IAM / CloudTrail)"),
                    ("okta", "Okta"),
                    ("google_workspace", "Google Workspace"),
                    ("slack", "Slack"),
                    ("github", "GitHub"),
                    ("agent_runtime", "Customer AI agent runtime (reported telemetry)"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="AgentTelemetrySource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("otlp_json", "OTLP/HTTP JSON spans (push)")], default="otlp_json", max_length=24
                    ),
                ),
                ("name", models.CharField(default="Agent telemetry", max_length=120)),
                ("platform", models.CharField(default="unknown", max_length=32)),
                ("agent_allowlist", models.JSONField(blank=True, default=list)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("secret_ref", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("error", "Error"),
                            ("disabled", "Disabled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("last_ingest_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_telemetry_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_telemetry_sources",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["workspace", "status"], name="agent_tel_src_ws_status_idx"),
                    models.Index(fields=["workspace", "kind"], name="agent_tel_src_ws_kind_idx"),
                ],
            },
        ),
    ]
