# Generated by Django 6.0.3 on 2026-08-02 03:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_kind', models.CharField(db_index=True, max_length=64)),
                ('source_type', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(blank=True, default='', max_length=48)),
                ('code', models.TextField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('finding_task_id', models.CharField(db_index=True, max_length=64)),
                ('finding_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('provenance_event_ref', models.CharField(blank=True, default='', max_length=255)),
                ('applied_pr_url', models.URLField(max_length=1024)),
                ('approved_by', models.CharField(max_length=64)),
                ('resolved_at', models.DateTimeField()),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_entries', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'finding_kind', '-created_at'], name='remediation_workspa_cb35ad_idx'), models.Index(fields=['workspace', 'is_deleted', '-created_at'], name='remediation_workspa_8c95e3_idx'), models.Index(fields=['workspace', 'finding_task_id'], name='remediation_workspa_ebb390_idx')],
            },
        ),
    ]
