# Generated by Django 6.0.3 on 2026-08-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0001_initial'),
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='remediationentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('workspace', 'finding_task_id'), name='uniq_active_remediation_per_finding'),
        ),
    ]
