# Generated by Django 6.0.3 on 2026-08-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0002_remediationentry_uniq_active_remediation_per_finding'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediationentry',
            name='last_outcome_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remediationentry',
            name='recurrence_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='remediationentry',
            name='reuse_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='remediationentry',
            name='success_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='remediationentry',
            name='score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
