# Generated by Django 6.0.3 on 2026-08-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0003_remediation_outcome_tracking_and_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediationentry',
            name='embedded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
