# Generated by Django 6.0.3 on 2026-07-18 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_domains'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('admin_added', 'Admin added'), ('self_subscribed', 'Self-subscribed (public widget)'), ('imported', 'Imported (bulk paste / CSV)'), ('directory_picked', 'Picked from workspace directory')], default='admin_added', max_length=24)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_subscribers', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'content_subscriber',
                'ordering': ('-subscribed_at',),
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('preheader', models.CharField(blank=True, max_length=255)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('content_html', models.TextField(blank=True)),
                ('content_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ai_drafted', 'AI-drafted (awaiting review)'), ('scheduled', 'Scheduled to send'), ('sending', 'Sending'), ('sent', 'Sent'), ('send_failed', 'Send failed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pdf_key', models.CharField(blank=True, max_length=512)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('ai_drafted_by_agent', models.CharField(blank=True, max_length=64)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('recipient_count', models.IntegerField(blank=True, null=True)),
                ('failed_count', models.IntegerField(blank=True, null=True)),
                ('unique_open_count', models.IntegerField(default=0)),
                ('total_open_count', models.IntegerField(default=0)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_newsletters', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='workspaces.workspace')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='newsletters', to='content.subscriber')),
            ],
            options={
                'db_table': 'content_newsletter',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SuppressedAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('reason', models.CharField(choices=[('hard_bounce', 'Hard bounce'), ('complaint', 'Spam complaint'), ('manual', 'Manually suppressed'), ('admin_removed', 'Admin removed subscriber')], max_length=24)),
                ('suppressed_at', models.DateTimeField(auto_now_add=True)),
                ('source_event', models.JSONField(blank=True, default=dict, help_text='SNS notification body or similar audit payload.')),
                ('workspace', models.ForeignKey(blank=True, help_text='NULL means system-wide (e.g., a permanently invalid address).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_suppressed_addresses', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'content_suppressed_address',
                'ordering': ('-suppressed_at',),
            },
        ),
        migrations.CreateModel(
            name='WritingDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body_html', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('letter', 'Letter'), ('update', 'Update'), ('summary', 'Summary'), ('memo', 'Memo'), ('blog', 'Blog'), ('recipient_update', 'Recipient update'), ('project_update', 'Project update'), ('event_update', 'Event update'), ('campaign_update', 'Campaign update')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('pdf_key', models.CharField(blank=True, max_length=512)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('ai_drafted', models.BooleanField(default=False)),
                ('related_entity_type', models.CharField(blank=True, choices=[('recipient', 'Recipient'), ('project', 'Project'), ('event', 'Event'), ('campaign', 'Campaign')], max_length=16)),
                ('related_entity_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_writing_drafts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_drafts', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'content_writing_draft',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailDispatchRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=8)),
                ('open_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('open_count', models.IntegerField(default=0)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_dispatch_records', to='workspaces.workspace')),
                ('newsletter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_records', to='content.newsletter')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_dispatch_records', to='content.writingdraft')),
            ],
            options={
                'db_table': 'content_email_dispatch_record',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WritingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('letter', 'Letter'), ('update', 'Update'), ('summary', 'Summary'), ('memo', 'Memo'), ('newsletter', 'Newsletter'), ('blog', 'Blog'), ('proposal', 'Proposal'), ('social', 'Social media')], db_index=True, max_length=16)),
                ('body_html', models.TextField(blank=True)),
                ('is_seeded', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writing_templates', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'content_writing_template',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='writingdraft',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='content.writingtemplate'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['workspace', 'is_active'], name='content_sub_workspa_e108c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('workspace', 'email'), name='content_subscriber_unique_workspace_email'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', True)), fields=('email',), name='content_subscriber_unique_email_when_no_workspace'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['workspace', 'status'], name='content_new_workspa_30ef15_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['workspace', '-created_at'], name='content_new_workspa_b0ebad_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['workspace', 'period_start', 'period_end'], name='content_new_workspa_f35312_idx'),
        ),
        migrations.AddIndex(
            model_name='suppressedaddress',
            index=models.Index(fields=['workspace', 'email'], name='content_sup_workspa_8bc6f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='suppressedaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('workspace', 'email'), name='content_suppressed_unique_workspace_email'),
        ),
        migrations.AddConstraint(
            model_name='suppressedaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', True)), fields=('email',), name='content_suppressed_unique_email_when_no_workspace'),
        ),
        migrations.AddIndex(
            model_name='emaildispatchrecord',
            index=models.Index(fields=['newsletter', 'status'], name='content_ema_newslet_63b084_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildispatchrecord',
            index=models.Index(fields=['draft', 'status'], name='content_ema_draft_i_3422e8_idx'),
        ),
        migrations.AddIndex(
            model_name='writingtemplate',
            index=models.Index(fields=['workspace', 'kind'], name='content_wri_workspa_efea86_idx'),
        ),
        migrations.AddIndex(
            model_name='writingtemplate',
            index=models.Index(fields=['kind', 'is_seeded'], name='content_wri_kind_de5d93_idx'),
        ),
        migrations.AddConstraint(
            model_name='writingtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('is_seeded', False), models.Q(('is_seeded', True), ('workspace__isnull', True)), _connector='OR'), name='content_writing_template_seeded_must_be_global'),
        ),
        migrations.AddIndex(
            model_name='writingdraft',
            index=models.Index(fields=['workspace', 'status'], name='content_wri_workspa_5f36b2_idx'),
        ),
        migrations.AddIndex(
            model_name='writingdraft',
            index=models.Index(fields=['workspace', 'kind', 'status'], name='content_wri_workspa_3dbd33_idx'),
        ),
        migrations.AddIndex(
            model_name='writingdraft',
            index=models.Index(fields=['workspace', 'author', '-updated_at'], name='content_wri_workspa_e20806_idx'),
        ),
        migrations.AddIndex(
            model_name='writingdraft',
            index=models.Index(fields=['workspace', 'related_entity_type', 'related_entity_id'], name='content_draft_related_idx'),
        ),
    ]
