# Generated by Django 6.0.3 on 2026-07-19 04:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
        ('team', '0003_team_plan'),
        ('workspaces', '0004_workspace_domains'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('team', 'workspace', 'title'), name='uniq_board_column_title_per_team'),
        ),
    ]
