# Generated by Django 6.0.3 on 2026-08-14 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_column_uniq_board_column_title_per_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectupdate',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
