# Generated by Django 6.0.3 on 2026-08-17 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_projectupdate_tags_remove_taskcomment_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['order', 'id']},
        ),
    ]
