# Generated by Django 6.0.3 on 2026-08-17 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_merge_done_into_complete'),
        ('team', '0005_seed_red_blue_teams'),
        ('workspaces', '0005_remove_workspacecomment_tags_alter_workspace_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('backlog', 'Backlog'), ('unstarted', 'Unstarted'), ('started', 'Started'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='started', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_statuses', to='team.team')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'verbose_name_plural': 'workflow statuses',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='column',
            name='workflow_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='columns', to='project.workflowstatus'),
        ),
        migrations.AddField(
            model_name='task',
            name='workflow_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='project.workflowstatus'),
        ),
        migrations.CreateModel(
            name='BoardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('filter', models.JSONField(blank=True, default=dict)),
                ('group_by', models.CharField(default='status', max_length=32)),
                ('order', models.IntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_views', to='team.team')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('team', 'workspace', 'slug'), name='uniq_board_view_slug_per_team')],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowstatus',
            constraint=models.UniqueConstraint(fields=('team', 'workspace', 'name'), name='uniq_workflow_status_name_per_team'),
        ),
    ]
