# Generated by Django 6.0.3 on 2026-07-24 20:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudPostureScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_id', models.UUIDField(blank=True, null=True)),
                ('account_id', models.CharField(max_length=32)),
                ('provider', models.CharField(default='aws', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=16)),
                ('engine_version', models.CharField(blank=True, default='', max_length=32)),
                ('total_checks', models.PositiveIntegerField(default=0)),
                ('passed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_posture_scans', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CloudPostureFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_id', models.CharField(max_length=128)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('informational', 'Informational')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('manual', 'Manual')], default='fail', max_length=8)),
                ('account_id', models.CharField(blank=True, default='', max_length=32)),
                ('region', models.CharField(blank=True, default='', max_length=32)),
                ('service', models.CharField(blank=True, default='', max_length=64)),
                ('resource_uid', models.CharField(blank=True, default='', max_length=512)),
                ('resource_name', models.CharField(blank=True, default='', max_length=255)),
                ('resource_type', models.CharField(blank=True, default='', max_length=128)),
                ('finding_uid', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('remediation', models.TextField(blank=True, default='')),
                ('compliance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_posture_findings', to='workspaces.workspace')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='cloud_posture.cloudposturescan')),
            ],
        ),
        migrations.AddIndex(
            model_name='cloudposturescan',
            index=models.Index(fields=['workspace', '-created_at'], name='cps_scan_ws_created_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudposturescan',
            index=models.Index(fields=['workspace', 'account_id', '-created_at'], name='cps_scan_ws_acct_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudposturefinding',
            index=models.Index(fields=['workspace', 'severity', '-created_at'], name='cps_finding_ws_sev_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudposturefinding',
            index=models.Index(fields=['scan', 'severity'], name='cps_finding_scan_sev_idx'),
        ),
        migrations.AddConstraint(
            model_name='cloudposturefinding',
            constraint=models.UniqueConstraint(fields=('scan', 'check_id', 'resource_uid'), name='uniq_cps_finding_per_scan_check_resource'),
        ),
    ]
