# Generated by Django 6.0.3 on 2026-08-14 04:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subdomain', models.SlugField(max_length=63, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('isolation_mode', models.CharField(choices=[('pooled', 'Pooled — shared database'), ('dedicated', 'Dedicated database')], default='pooled', max_length=16)),
                ('db_alias', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenancy_tenant',
                'ordering': ['subdomain'],
                'indexes': [models.Index(fields=['subdomain', 'is_active'], name='tenant_subdomain_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('subdomain__in', ['admin', 'api', 'app', 'assets', 'auth', 'cdn', 'localhost', 'mail', 'static', 'status', 'www']), _negated=True), name='tenant_subdomain_not_reserved'), models.CheckConstraint(condition=models.Q(models.Q(('isolation_mode', 'dedicated'), models.Q(('db_alias', ''), _negated=True)), models.Q(('isolation_mode', 'pooled'), ('db_alias', '')), _connector='OR'), name='tenant_db_alias_matches_isolation_mode')],
            },
        ),
    ]
