# Generated by Django 6.0.3 on 2026-08-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='workspace_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
