# Generated by Django 6.0.3 on 2026-07-25 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=64)),
                ('fingerprint', models.CharField(max_length=255)),
                ('asset_urn', models.CharField(max_length=512)),
                ('severity', models.CharField(max_length=16)),
                ('status', models.CharField(default='open', max_length=16)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('remediation', models.TextField(blank=True, default='')),
                ('compliance', models.JSONField(default=dict, help_text="Framework tags, e.g. {'CIS-2.0': ['2.1.5']}.")),
                ('attributes', models.JSONField(default=dict, help_text='Pillar-specific extras.')),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'severity', '-last_seen_at'], name='finding_ws_sev_seen_idx'), models.Index(fields=['workspace', 'status', '-last_seen_at'], name='finding_ws_status_seen_idx'), models.Index(fields=['workspace', 'asset_urn'], name='finding_ws_urn_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'source', 'fingerprint'), name='uniq_finding_identity')],
            },
        ),
    ]
