# Generated by Django 6.0.3 on 2026-07-27 17:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAttckCoverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coverage', models.JSONField(default=dict, help_text='The heatmap blob: tactics → techniques with counts.')),
                ('technique_count', models.IntegerField(default=0)),
                ('finding_count', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField()),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attck_coverage', to='workspaces.workspace')),
            ],
        ),
    ]
