# Generated by Django 6.0.3 on 2026-08-03 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0002_workspaceattckcoverage'),
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0, help_text='0–100 contextual risk (higher = more urgent).')),
                ('band', models.CharField(help_text='RiskBand.value — green | amber | red.', max_length=8)),
                ('factors', models.JSONField(default=list, help_text='RiskFactor breakdown [{key,label,points,detail}].')),
                ('epss', models.FloatField(blank=True, help_text='EPSS probability [0-1], or null if no CVE match.', null=True)),
                ('epss_percentile', models.FloatField(blank=True, null=True)),
                ('in_kev', models.BooleanField(default=False, help_text='CVE is in the CISA KEV catalog (confirmed exploited).')),
                ('exposure', models.CharField(default='private', help_text='Applied amplifier bucket.', max_length=16)),
                ('exposure_unknown', models.BooleanField(default=False, help_text='No graph signal — damped to private but flagged (ADR 0013 decision #3).')),
                ('model_version', models.CharField(default='', help_text='Scorer blend version.', max_length=32)),
                ('epss_score_date', models.CharField(blank=True, default='', help_text='EPSS snapshot date scored against.', max_length=16)),
                ('kev_catalog_version', models.CharField(blank=True, default='', help_text='KEV catalog version scored against.', max_length=32)),
                ('scored_at', models.DateTimeField()),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk', to='findings.finding')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_risks', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', '-score'], name='finding_risk_ws_score_idx'), models.Index(fields=['workspace', 'in_kev'], name='finding_risk_ws_kev_idx')],
            },
        ),
    ]
