# Generated by Django 6.0.3 on 2026-08-04 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0003_findingrisk'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='status_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='finding',
            name='suppress_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FindingTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applied_by', models.UUIDField(blank=True, null=True)),
                ('source', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('rule', 'Rule'), ('system', 'System')], default='user', max_length=16)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='findings.finding')),
            ],
        ),
    ]
