# Generated by Django 6.0.3 on 2026-08-04 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0004_finding_status_reason_finding_suppress_expires_at_and_more'),
        ('tagging', '0001_initial'),
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_links', to='tagging.tag'),
        ),
        migrations.AddField(
            model_name='findingtag',
            name='workspace',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='finding_tags', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='findingtag',
            index=models.Index(fields=['workspace', 'tag'], name='findingtag_ws_tag_idx'),
        ),
        migrations.AddConstraint(
            model_name='findingtag',
            constraint=models.UniqueConstraint(fields=('finding', 'tag'), name='uniq_finding_tag'),
        ),
    ]
