# Generated by Django 6.0.3 on 2026-08-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0005_findingtag_tag_findingtag_workspace_and_more'),
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='scan_run_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['workspace', 'scan_run_id'], name='finding_ws_run_idx'),
        ),
    ]
