# Generated by Django 6.0.3 on 2026-08-17 19:49

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0006_finding_scan_run_id_finding_finding_ws_run_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finding',
            options={'base_manager_name': 'unscoped'},
        ),
        migrations.AlterModelManagers(
            name='finding',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
