# Generated by Django 6.0.3 on 2026-08-07 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoScanSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_run_id', models.UUIDField(unique=True)),
                ('repo', models.CharField(max_length=200)),
                ('commit_sha', models.CharField(blank=True, default='', max_length=64)),
                ('engine_version', models.CharField(blank=True, default='', max_length=32)),
                ('total_findings', models.PositiveIntegerField(default=0)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('high_count', models.PositiveIntegerField(default=0)),
                ('medium_count', models.PositiveIntegerField(default=0)),
                ('low_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_scan_snapshots', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'repo', '-created_at'], name='reposcan_ws_repo_created_idx')],
            },
        ),
    ]
