# Generated by Django 6.0.3 on 2026-07-18 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_domains'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwsOrganizationConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='AWS Organization', max_length=120)),
                ('management_account_id', models.CharField(max_length=12)),
                ('organization_id', models.CharField(blank=True, default='', max_length=34)),
                ('role_name', models.CharField(default='AutoSecAuditRole', max_length=128)),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('regions', models.JSONField(default=list, help_text='Regions to ingest from; empty = all enabled.')),
                ('org_wide', models.BooleanField(default=True)),
                ('trail_s3_bucket', models.CharField(blank=True, default='', max_length=255)),
                ('trail_s3_prefix', models.CharField(blank=True, default='', max_length=255)),
                ('sqs_queue_url', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending — template not yet deployed'), ('verifying', 'Verifying role assumption'), ('connected', 'Connected'), ('degraded', 'Degraded — some accounts failing'), ('error', 'Error'), ('disabled', 'Disabled')], default='pending', max_length=16)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aws_connections', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='AwsAccountLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=12)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('verified', 'Role verified'), ('failed', 'Assume-role failing'), ('suspended', 'Suspended in org'), ('excluded', 'Excluded by operator')], default='discovered', max_length=16)),
                ('last_assumed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='integrations.awsorganizationconnection')),
            ],
        ),
        migrations.CreateModel(
            name='IngestCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(blank=True, default='', max_length=12)),
                ('region', models.CharField(blank=True, default='', max_length=32)),
                ('channel', models.CharField(choices=[('sqs', 'SQS notifications (primary)'), ('s3_list', 'S3 prefix listing (fallback)')], default='sqs', max_length=16)),
                ('last_object_key', models.CharField(blank=True, default='', max_length=1024)),
                ('last_event_time', models.DateTimeField(blank=True, null=True)),
                ('objects_processed', models.BigIntegerField(default=0)),
                ('events_processed', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='integrations.awsorganizationconnection')),
            ],
        ),
        migrations.CreateModel(
            name='SinkConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('slack', 'Slack'), ('webhook', 'Generic webhook')], max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('secret_ciphertext', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sink_connectors', to='workspaces.workspace')),
            ],
        ),
        migrations.AddIndex(
            model_name='awsorganizationconnection',
            index=models.Index(fields=['workspace', 'status'], name='integration_workspa_faae54_idx'),
        ),
        migrations.AddConstraint(
            model_name='awsorganizationconnection',
            constraint=models.UniqueConstraint(fields=('workspace', 'management_account_id'), name='uniq_ws_aws_mgmt_account'),
        ),
        migrations.AddIndex(
            model_name='awsaccountlink',
            index=models.Index(fields=['connection', 'status'], name='integration_connect_2b4fd5_idx'),
        ),
        migrations.AddConstraint(
            model_name='awsaccountlink',
            constraint=models.UniqueConstraint(fields=('connection', 'account_id'), name='uniq_conn_account'),
        ),
        migrations.AddConstraint(
            model_name='ingestcheckpoint',
            constraint=models.UniqueConstraint(fields=('connection', 'account_id', 'region', 'channel'), name='uniq_ingest_cursor'),
        ),
        migrations.AddIndex(
            model_name='sinkconnector',
            index=models.Index(fields=['workspace', 'kind', 'is_enabled'], name='integration_workspa_3ec1df_idx'),
        ),
    ]
