# Generated by Django 6.0.3 on 2026-07-19 04:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPatternRollup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(default='', max_length=120)),
                ('signature', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('periodic_task', 'Scheduled/periodic task'), ('health_check', 'Health-check / housekeeping noise'), ('volume', 'High-volume service chatter'), ('other', 'Other recurring pattern')], default='other', max_length=16)),
                ('sample_message', models.CharField(blank=True, default='', max_length=500)),
                ('total_count', models.BigIntegerField(default=0)),
                ('last_window_count', models.IntegerField(default=0)),
                ('peak_window_count', models.IntegerField(default=0)),
                ('runs_observed', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_flagged_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_pattern_rollups', to='integrations.awsorganizationconnection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_pattern_rollups', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'kind'], name='integration_workspa_15fab6_idx')],
                'constraints': [models.UniqueConstraint(fields=('connection', 'signature'), name='uniq_conn_log_signature')],
            },
        ),
    ]
