# Generated by Django 6.0.3 on 2026-07-19 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_logpatternrollup'),
        ('workspaces', '0004_workspace_domains'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='GitHub', max_length=120)),
                ('repo_allowlist', models.JSONField(blank=True, default=list)),
                ('token_ciphertext', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disabled', 'Disabled'), ('error', 'Error')], default='connected', max_length=16)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_connections', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'status'], name='integration_workspa_c3b8a8_idx')],
            },
        ),
    ]
