# Generated by Django 6.0.3 on 2026-07-20 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_githubconnection'),
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMetricBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('auth_failure', 'Authentication failure (failed logins / SSH attempts / invalid user)'), ('http_5xx', 'HTTP 5xx server error responses'), ('http_4xx', 'HTTP 4xx client error responses'), ('sqli_signature', "SQL-injection-shaped payload (UNION SELECT, ' OR 1=1, …)"), ('scanner', 'Scanner user agents / probing paths (sqlmap, nikto, /wp-admin, /.env)'), ('app_error', 'ERROR-level application log lines'), ('app_warning', 'WARNING-level application log lines'), ('total_volume', 'All log lines (lines/day + DDoS volume baseline)')], max_length=32)),
                ('service', models.CharField(default='', max_length=120)),
                ('source', models.CharField(default='', max_length=64)),
                ('bucket_start', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
                ('sample_message', models.CharField(blank=True, default='', max_length=500)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_metric_buckets', to='integrations.awsorganizationconnection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_metric_buckets', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'metric', 'bucket_start'], name='integration_workspa_918b7c_idx')],
                'constraints': [models.UniqueConstraint(fields=('connection', 'metric', 'service', 'source', 'bucket_start'), name='uniq_log_metric_bucket')],
            },
        ),
    ]
