# Generated by Django 6.0.3 on 2026-07-31 03:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_logmetricbucket'),
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceLogSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('s3', 'Amazon S3 trail'), ('cloudwatch', 'Amazon CloudWatch Logs'), ('datadog', 'Datadog'), ('splunk', 'Splunk'), ('webhook', 'HTTP webhook (push)')], max_length=16)),
                ('name', models.CharField(default='', max_length=120)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('secret_ref', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('error', 'Error'), ('disabled', 'Disabled')], default='draft', max_length=16)),
                ('cursor', models.CharField(blank=True, default='', max_length=1024)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sources', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'status'], name='integration_workspa_718a73_idx'), models.Index(fields=['workspace', 'kind'], name='integration_workspa_f90f5c_idx')],
            },
        ),
    ]
