# Generated by Django 6.0.3 on 2026-08-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_migrate_github_connections_to_vcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcsconnection',
            name='repo_root',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
