# Generated by Django 6.0.3 on 2026-08-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_vcsconnection_repo_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcsconnection',
            name='commit_author_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='vcsconnection',
            name='commit_author_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='vcsconnection',
            name='commit_identity',
            field=models.CharField(choices=[('pat_owner', 'PAT owner (default — no author/committer sent)'), ('operator', 'The approving operator (their name + email)'), ('custom', 'A fixed custom name + email')], default='pat_owner', max_length=16),
        ),
    ]
