"""Rename SinkConnector -> DeliveryConnection and productize it (ADR 0016 D2).

Hand-written rather than autogenerated for two reasons: ``makemigrations`` cannot
infer a model rename non-interactively (it would emit delete+create and drop every
existing row), and the ``min_severity`` promotion needs a real backfill —
a bare ``AddField(default="high")`` would silently discard the floor of any
connection an operator had set to ``critical``.
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import infrastructure.persistence.integrations.models as integrations_models


def forwards_backfill_existing_rows(apps, schema_editor):
    """Preserve what hand-created rows already meant.

    Two things would otherwise regress silently:

    * ``min_severity`` lived in ``config``; a bare AddField default would discard a
      floor an operator had set to ``critical`` and start paging them on ``high``.
    * every row that exists today authenticates with a **bot token** (webhook mode
      is new in this migration), so the ``webhook_url`` column default is wrong for
      all of them — left uncorrected, the first delivery after deploy would try to
      POST a bot token as if it were a URL and fail permanently.
    """
    DeliveryConnection = apps.get_model("integrations", "DeliveryConnection")
    for row in DeliveryConnection.objects.all().iterator(chunk_size=500):
        config = dict(row.config or {})
        stored = str(config.pop("min_severity", "") or "").strip().lower()
        if stored:
            row.min_severity = stored
            row.config = config
        row.auth_mode = "bot_token"
        row.save(update_fields=["min_severity", "config", "auth_mode"])


def backwards_demote_min_severity(apps, schema_editor):
    """Put the floor back into config so a rollback keeps delivering correctly."""
    DeliveryConnection = apps.get_model("integrations", "DeliveryConnection")
    for row in DeliveryConnection.objects.all().iterator(chunk_size=500):
        config = dict(row.config or {})
        config["min_severity"] = row.min_severity
        row.config = config
        row.save(update_fields=["config"])


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0010_vcsconnection_commit_author_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(old_name="SinkConnector", new_name="DeliveryConnection"),
        migrations.AlterField(
            model_name="deliveryconnection",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_connections",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="deliveryconnection",
            name="auth_mode",
            field=models.CharField(
                choices=[("webhook_url", "Incoming webhook URL"), ("bot_token", "Bot token")],
                default="webhook_url",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="deliveryconnection",
            name="events",
            field=models.JSONField(blank=True, default=integrations_models.default_delivery_events),
        ),
        migrations.AddField(
            model_name="deliveryconnection",
            name="min_severity",
            field=models.CharField(default="high", max_length=16),
        ),
        migrations.AddField(
            model_name="deliveryconnection",
            name="status",
            field=models.CharField(
                choices=[("connected", "Connected"), ("disabled", "Disabled"), ("error", "Error")],
                default="connected",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="deliveryconnection",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryconnection",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Index names are derived from the model name, so the inherited index has to
        # be renamed alongside the model or Django keeps detecting drift forever.
        migrations.RenameIndex(
            model_name="deliveryconnection",
            old_name="integration_workspa_3ec1df_idx",
            new_name="integration_workspa_3b0ea7_idx",
        ),
        migrations.AddIndex(
            model_name="deliveryconnection",
            index=models.Index(fields=["workspace", "status"], name="integration_workspa_d7f837_idx"),
        ),
        migrations.RunPython(
            forwards_backfill_existing_rows,
            backwards_demote_min_severity,
        ),
    ]
