# Generated by Django 6.0.3 on 2026-08-09 04:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_deliveryconnection'),
        ('workspaces', '0004_workspace_domains'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VercelConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Vercel', max_length=120)),
                ('team_id', models.CharField(blank=True, default='', max_length=64)),
                ('team_slug', models.CharField(blank=True, default='', max_length=64)),
                ('team_name', models.CharField(blank=True, default='', max_length=255)),
                ('credential_kind', models.CharField(choices=[('token', 'API token'), ('oauth_integration', 'OAuth connectable integration (P4 — not yet available)')], default='token', max_length=24)),
                ('token_ciphertext', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disabled', 'Disabled'), ('error', 'Error')], default='connected', max_length=16)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vercel_connections', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'status'], name='integration_workspa_e61002_idx')],
            },
        ),
    ]
