# Generated by Django 6.0.3 on 2026-08-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_vercelconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcsconnection',
            name='auth_mode',
            field=models.CharField(choices=[('pat', 'Personal access token (encrypted, stored)'), ('github_app', 'GitHub App installation (short-lived tokens)')], default='pat', max_length=16),
        ),
        migrations.AddField(
            model_name='vcsconnection',
            name='installation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
