# Generated by Django 6.0.3 on 2026-04-22 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0002_initial"),
        # Retargeted to the fork's team/workspaces leaves (source-repo
        # 0006/0014 don't exist here; these deps are ordering-only).
        ("team", "0003_team_plan"),
        ("workspaces", "0004_workspace_domains"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="edited_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="edited_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="team",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="posts", to="team.team"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[("workspace", "Workspace"), ("team", "Team"), ("public", "Public")],
                default="workspace",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["workspace", "-created_on"], name="social_post_workspa_f96d60_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["team", "-created_on"], name="social_post_team_id_337c6e_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["author", "-created_on"], name="social_post_author__c41988_idx"),
        ),
    ]
