# Generated by Django 6.0.3 on 2026-08-14 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_comment_generic_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
