# Generated by Django 6.0.3 on 2026-07-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(default='Canada', max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'country',
                'ordering': ('name',),
            },
        ),
    ]
