# Generated by Django 6.0.3 on 2026-07-16 23:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleBinEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('entity_name', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('trashed', 'Trashed'), ('tombstoned', 'Tombstoned')], default='trashed', max_length=16)),
                ('deleted_at', models.DateTimeField()),
                ('trashed_until', models.DateTimeField()),
                ('tombstoned_at', models.DateTimeField(blank=True, null=True)),
                ('tombstoned_until', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('cascade_snapshot', models.JSONField(blank=True, default=dict)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recycle_bin',
            },
        ),
    ]
