# Generated by Django 6.0.3 on 2026-07-16 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recycle_bin', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclebinentry',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recyclebinentry',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recyclebinentry',
            name='tombstoned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recyclebinentry',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycle_bin_entries', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='recyclebinentry',
            index=models.Index(fields=['workspace', 'stage', '-deleted_at'], name='rb_ws_stage_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='recyclebinentry',
            index=models.Index(fields=['entity_type', 'entity_id'], name='rb_entity_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='recyclebinentry',
            index=models.Index(fields=['stage', 'trashed_until'], name='rb_tombstone_cron_idx'),
        ),
        migrations.AddIndex(
            model_name='recyclebinentry',
            index=models.Index(fields=['stage', 'tombstoned_until'], name='rb_purge_cron_idx'),
        ),
        migrations.AddConstraint(
            model_name='recyclebinentry',
            constraint=models.UniqueConstraint(fields=('entity_type', 'entity_id'), name='rb_unique_entity'),
        ),
    ]
