# Generated by Django 6.0.3 on 2026-07-29 04:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_domains'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandFontOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=48, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('heading', 'Heading'), ('body', 'Body'), ('both', 'Both')], default='both', max_length=16)),
                ('css_stack', models.CharField(max_length=255)),
                ('google_family', models.CharField(blank=True, default='', max_length=128)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'brand_font_option',
                'ordering': ('sort_order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_seed', models.CharField(blank=True, default='', max_length=9)),
                ('secondary_seed', models.CharField(blank=True, default='', max_length=9)),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('logo_icon_url', models.CharField(blank=True, default='', max_length=500)),
                ('logo_dark_url', models.CharField(blank=True, default='', max_length=500)),
                ('favicon_url', models.CharField(blank=True, default='', max_length=500)),
                ('font_heading', models.CharField(blank=True, default='', max_length=48)),
                ('font_body', models.CharField(blank=True, default='', max_length=48)),
                ('voice_tone', models.CharField(blank=True, choices=[('formal', 'Formal'), ('warm', 'Warm'), ('activist', 'Activist'), ('technical', 'Technical')], default='', max_length=24)),
                ('voice_guidelines', models.TextField(blank=True, default='')),
                ('mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=8)),
                ('radius', models.CharField(blank=True, default='', max_length=16)),
                ('login_branding_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspace_theme',
            },
        ),
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('storage_key', models.CharField(blank=True, default='', max_length=500)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('logo', 'Logo'), ('graphic', 'Graphic')], default='photo', max_length=16)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_assets', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'brand_asset',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', 'deleted', '-created_at'], name='brand_asset_workspa_d8cad6_idx')],
            },
        ),
    ]
