# Generated by Django 6.0.3 on 2026-07-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(blank=True, max_length=512)),
                ('import_type', models.CharField(choices=[('expense', 'Expenses'), ('income', 'Income'), ('budget', 'Budget'), ('recipient', 'Recipients'), ('donation', 'Donations'), ('event', 'Events'), ('campaign', 'Campaigns'), ('project', 'Projects'), ('contact', 'Contacts'), ('other', 'Other')], db_index=True, default='expense', max_length=32)),
                ('source_format', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('docx', 'Word (DOCX)'), ('doc', 'Word (DOC)'), ('xlsx', 'Excel (XLSX)'), ('xls', 'Excel (XLS)'), ('json', 'JSON'), ('txt', 'Text'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('parsing', 'Parsing'), ('needs_review', 'Needs Review'), ('ready', 'Ready'), ('applied', 'Applied'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('valid_row_count', models.PositiveIntegerField(default=0)),
                ('applied_row_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Import-type-specific config (e.g. budget_id, target entity).')),
                ('use_ai', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(db_index=True, default=0)),
                ('label', models.CharField(blank=True, max_length=512)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255)),
                ('row_type', models.CharField(blank=True, default='expense', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(blank=True, default=dict, help_text='Full parsed data from LLM/parser. Schema varies by import_type.')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Original raw data before parsing/normalisation.')),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('user_modified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('applied', 'Applied'), ('skipped', 'Skipped')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['row_index', 'created_at'],
            },
        ),
    ]
