# Generated by Django 6.0.3 on 2026-07-16 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentimport',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_imports', to='uploads.file'),
        ),
    ]
