# Generated by Django 6.0.3 on 2026-07-16 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0002_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentimport',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentimport',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_imports', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='documentimportrow',
            name='document_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.documentimport'),
        ),
        migrations.AddIndex(
            model_name='documentimport',
            index=models.Index(fields=['workspace', 'status'], name='docimport_ws_status'),
        ),
        migrations.AddIndex(
            model_name='documentimport',
            index=models.Index(fields=['workspace', 'import_type'], name='docimport_ws_type'),
        ),
        migrations.AddIndex(
            model_name='documentimport',
            index=models.Index(fields=['status', 'created_at'], name='docimport_status_created'),
        ),
        migrations.AddIndex(
            model_name='documentimportrow',
            index=models.Index(fields=['document_import', 'row_index'], name='docimport_row_idx'),
        ),
        migrations.AddIndex(
            model_name='documentimportrow',
            index=models.Index(fields=['document_import', 'status'], name='docimport_row_status'),
        ),
    ]
