# Generated by Django 6.0.3 on 2026-07-16 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0002_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_agents', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='agentcomment',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ai.agent'),
        ),
        migrations.AddField(
            model_name='agentcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ai.agentcomment'),
        ),
        migrations.AddField(
            model_name='agentcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ai.agent'),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_agent_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentfollow',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='ai.agent'),
        ),
        migrations.AddField(
            model_name='agentfollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='ai.agent'),
        ),
        migrations.AddField(
            model_name='agentrating',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ai.agent'),
        ),
        migrations.AddField(
            model_name='agentrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentreaction',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='ai.agent'),
        ),
        migrations.AddField(
            model_name='agentreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentshare',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='ai.agent'),
        ),
        migrations.AddField(
            model_name='aipermissiongrant',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_permission_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aipermissiongrant',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_permission_grants', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='aiteammateprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_teammate_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiteammateprofile',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_teammate_profile', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='deeprun',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deep_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deeprun',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deep_runs', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='deepartifact',
            name='deep_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ai.deeprun'),
        ),
        migrations.AddField(
            model_name='deeprunlog',
            name='deep_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ai.deeprun'),
        ),
        migrations.AddField(
            model_name='document',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai.document'),
        ),
        migrations.AddIndex(
            model_name='embeddingchunk',
            index=models.Index(fields=['-created_at'], name='ai_emb_chunk_created_idx'),
        ),
        migrations.AddField(
            model_name='workspaceagenttype',
            name='agent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_entitlements', to='ai.agenttype'),
        ),
        migrations.AddField(
            model_name='workspaceagenttype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_entitlement_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspaceagenttype',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_entitlements', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['user', 'workspace'], name='ai_agent_user_id_c02b52_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['agent_type', 'status'], name='ai_agent_agent_t_719758_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['created_at'], name='ai_agent_created_a134fd_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcomment',
            index=models.Index(fields=['agent', 'user'], name='ai_agentcom_agent_i_7790d7_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcomment',
            index=models.Index(fields=['created_at'], name='ai_agentcom_created_d327bf_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['agent', 'created_at'], name='ai_agentexe_agent_i_a55c55_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['status', 'created_at'], name='ai_agentexe_status_a7b133_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['success', 'created_at'], name='ai_agentexe_success_44f051_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['task_id'], name='ai_agentexe_task_id_635379_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['triggered_by'], name='ai_execution_trigger_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfollow',
            index=models.Index(fields=['agent', 'user'], name='ai_agentfol_agent_i_0cfb13_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfollow',
            index=models.Index(fields=['created_at'], name='ai_agentfol_created_18bb8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentfollow',
            unique_together={('agent', 'user')},
        ),
        migrations.AddIndex(
            model_name='agentrating',
            index=models.Index(fields=['agent', 'user'], name='ai_agentrat_agent_i_90e79c_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrating',
            index=models.Index(fields=['created_at'], name='ai_agentrat_created_ccdb23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentrating',
            unique_together={('agent', 'user')},
        ),
        migrations.AddIndex(
            model_name='agentreaction',
            index=models.Index(fields=['agent', 'user'], name='ai_agentrea_agent_i_af1dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='agentreaction',
            index=models.Index(fields=['reaction_type'], name='ai_agentrea_reactio_31434d_idx'),
        ),
        migrations.AddIndex(
            model_name='agentreaction',
            index=models.Index(fields=['created_at'], name='ai_agentrea_created_da4c75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentreaction',
            unique_together={('agent', 'user', 'reaction_type')},
        ),
        migrations.AddIndex(
            model_name='agentshare',
            index=models.Index(fields=['share_token'], name='ai_agentsha_share_t_ae6910_idx'),
        ),
        migrations.AddIndex(
            model_name='agentshare',
            index=models.Index(fields=['agent', 'created_at'], name='ai_agentsha_agent_i_a5cf9f_idx'),
        ),
        migrations.AddIndex(
            model_name='aipermissiongrant',
            index=models.Index(fields=['workspace', 'role', 'status'], name='ai_perm_ws_role_status_idx'),
        ),
        migrations.AddIndex(
            model_name='aipermissiongrant',
            index=models.Index(fields=['principal', 'status'], name='ai_perm_principal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='aipermissiongrant',
            index=models.Index(fields=['scope_type', 'scope_id'], name='ai_perm_scope_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aipermissiongrant',
            unique_together={('workspace', 'principal', 'role', 'scope_type', 'scope_id')},
        ),
        migrations.AddIndex(
            model_name='aiteammateprofile',
            index=models.Index(fields=['status'], name='ai_teammate_status_idx'),
        ),
        migrations.AddIndex(
            model_name='aiteammateprofile',
            index=models.Index(fields=['user'], name='ai_teammate_user_idx'),
        ),
        migrations.AddIndex(
            model_name='deeprun',
            index=models.Index(fields=['thread_id'], name='ai_deeprun_thread__f6e99a_idx'),
        ),
        migrations.AddIndex(
            model_name='deeprun',
            index=models.Index(fields=['plan_id'], name='ai_deeprun_plan_id_5144a8_idx'),
        ),
        migrations.AddIndex(
            model_name='deeprun',
            index=models.Index(fields=['status', 'updated_at'], name='ai_deeprun_status_e51107_idx'),
        ),
        migrations.AddIndex(
            model_name='deepartifact',
            index=models.Index(fields=['deep_run', 'task_id'], name='ai_deeparti_deep_ru_10ef06_idx'),
        ),
        migrations.AddIndex(
            model_name='deeprunlog',
            index=models.Index(fields=['deep_run', 'created_at'], name='deep_run_log_run_idx'),
        ),
        migrations.AddIndex(
            model_name='deeprunlog',
            index=models.Index(fields=['event_type', 'created_at'], name='deep_run_log_evt_idx'),
        ),
        migrations.AddIndex(
            model_name='deeprunlog',
            index=models.Index(fields=['agent_type', 'created_at'], name='deep_run_log_agent_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='ai_document_created_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['source'], name='ai_document_source_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', '-created_at'], name='ai_doc_ws_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='ai_chunk_doc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
        migrations.AddIndex(
            model_name='workspaceagenttype',
            index=models.Index(fields=['workspace', 'is_enabled'], name='ai_workspace_agent_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceagenttype',
            index=models.Index(fields=['agent_type', 'is_enabled'], name='ai_agent_type_enabled_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspaceagenttype',
            unique_together={('workspace', 'agent_type')},
        ),
    ]
