# Generated by Django 6.0.3 on 2026-07-21 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_initial'),
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiActionDailyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('runs_total', models.PositiveIntegerField(default=0)),
                ('runs_completed', models.PositiveIntegerField(default=0)),
                ('runs_failed', models.PositiveIntegerField(default=0)),
                ('tool_calls', models.PositiveIntegerField(default=0)),
                ('tokens_input', models.PositiveBigIntegerField(default=0)),
                ('tokens_output', models.PositiveBigIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_action_daily_rollups', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['workspace', '-date'], name='ai_action_rollup_ws_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'date'), name='uniq_ws_date_ai_action_rollup')],
            },
        ),
    ]
