# Generated by Django 6.0.3 on 2026-08-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_embeddingchunk_embedding_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
