# Generated by Django 6.0.3 on 2026-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0005_embeddingchunk_embedding_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="deeprunlog",
            name="prompt_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="deeprunlog",
            name="prompt_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
