# Generated by Django 6.0.3 on 2026-08-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_deeprunlog_prompt_id_deeprunlog_prompt_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='deeprun',
            name='autonomy_mode',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
