# Generated by Django 6.0.3 on 2026-08-06 00:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSbom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_run_id', models.UUIDField(unique=True)),
                ('image_ref', models.CharField(max_length=512)),
                ('image_ref_digest', models.CharField(blank=True, default='', max_length=64)),
                ('format', models.CharField(default='cyclonedx', max_length=16)),
                ('spec_version', models.CharField(blank=True, default='', max_length=16)),
                ('bucket', models.CharField(max_length=128)),
                ('object_key', models.CharField(max_length=512)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('package_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_sboms', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='imagesbom_ws_created_idx')],
            },
        ),
    ]
