# Generated by Django 6.0.3 on 2026-07-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=32)),
                ('org_slug', models.CharField(blank=True, default='', max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('stripe_account_id', models.CharField(blank=True, default='', max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('provisioned_by', models.CharField(blank=True, default='', max_length=120)),
                ('is_canonical', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('torn_down', 'Torn down')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=150, unique=True)),
                ('default_enabled', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('workspace', 'Workspace'), ('user', 'User')], max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('flag__key', 'scope', '-updated_at'),
            },
        ),
    ]
