# Generated by Django 6.0.3 on 2026-07-16 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demoaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demoaccount',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_accounts', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='featureflagrule',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.featureflag'),
        ),
        migrations.AddField(
            model_name='featureflagrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_feature_flag_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureflagrule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flag_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureflagrule',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flag_rules', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='demoaccount',
            index=models.Index(fields=['status', 'expires_at'], name='core_demoac_status_975960_idx'),
        ),
        migrations.AddConstraint(
            model_name='featureflagrule',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'global')), fields=('flag', 'scope'), name='uniq_feature_flag_global_rule'),
        ),
        migrations.AddConstraint(
            model_name='featureflagrule',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'workspace')), fields=('flag', 'scope', 'workspace'), name='uniq_feature_flag_workspace_rule'),
        ),
        migrations.AddConstraint(
            model_name='featureflagrule',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'user')), fields=('flag', 'scope', 'user'), name='uniq_feature_flag_user_rule'),
        ),
        migrations.AddConstraint(
            model_name='featureflagrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'global'), ('user__isnull', True), ('workspace__isnull', True)), models.Q(('scope', 'workspace'), ('user__isnull', True), ('workspace__isnull', False)), models.Q(('scope', 'user'), ('user__isnull', False), ('workspace__isnull', True)), _connector='OR'), name='feature_flag_rule_scope_requires_target'),
        ),
    ]
