# Generated by Django 6.0.3 on 2026-07-25 02:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('workspaces', '0004_workspace_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('phase', models.CharField(blank=True, default='', max_length=64)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_jobs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', 'status', '-created_at'], name='bgjob_ws_status_idx'), models.Index(fields=['workspace', 'job_type', '-created_at'], name='bgjob_ws_type_idx')],
            },
        ),
    ]
