# Generated by Django 6.0.3 on 2026-07-16 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('users', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorprofile',
            name='contribution_means',
            field=models.ManyToManyField(blank=True, related_name='contributors', to='workspaces.contributionmeans'),
        ),
        migrations.AddField(
            model_name='contributorprofile',
            name='preferred_locations',
            field=models.ManyToManyField(blank=True, related_name='contributors', to='countries.country'),
        ),
        migrations.AddField(
            model_name='contributorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='magiclinktoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.country'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authauditevent',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='users.usersession'),
        ),
        migrations.AddField(
            model_name='workspaceloginactivityexclusion',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_exclusions', to='users.authauditevent'),
        ),
        migrations.AddField(
            model_name='workspaceloginactivityexclusion',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_login_activity_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspaceloginactivityexclusion',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_activity_exclusions', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='magiclinktoken',
            index=models.Index(fields=['email', '-created_at'], name='mlink_email_created_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-last_seen_at'], name='usersession_user_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'revoked_at'], name='usersession_user_revoked_idx'),
        ),
        migrations.AddIndex(
            model_name='authauditevent',
            index=models.Index(fields=['event_code', 'created_at'], name='auth_audit_event_idx'),
        ),
        migrations.AddIndex(
            model_name='authauditevent',
            index=models.Index(fields=['email', 'created_at'], name='auth_audit_email_idx'),
        ),
        migrations.AddIndex(
            model_name='authauditevent',
            index=models.Index(fields=['user', '-created_at'], name='auth_audit_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspaceloginactivityexclusion',
            constraint=models.UniqueConstraint(fields=('workspace', 'event'), name='uniq_ws_login_activity_exclusion'),
        ),
    ]
